/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.com.asofar.views.prestacionesporservicios;

import ec.com.asofar.dao.InPrestacionesPorServiciosJpaController;
import ec.com.asofar.dao.PrPrestacionesJpaController;
import ec.com.asofar.dao.VeUnidadServicioJpaController;
import ec.com.asofar.daoext.ObtenerDTO;
import ec.com.asofar.daoext.ValidarDTO;
import ec.com.asofar.dto.InPrestacionesPorServicios;
import ec.com.asofar.dto.PrArticulo;
import ec.com.asofar.dto.PrPrestaciones;
import ec.com.asofar.dto.PrSubgrupos;
import ec.com.asofar.dto.SeEmpresa;
import ec.com.asofar.dto.SeSucursal;
import ec.com.asofar.dto.SeUsuarios;
import ec.com.asofar.dto.VeUnidadServicio;
import ec.com.asofar.util.EntityManagerUtil;
import ec.com.asofar.views.prestaciones.Consulta_prestaciones;
import java.awt.MouseInfo;
import java.awt.Point;
import java.math.BigInteger;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import static jdk.nashorn.internal.runtime.Debug.id;

public class ActualizarPrestaciones extends javax.swing.JDialog {

    int x, y;
    InPrestacionesPorServicios pol1 = new InPrestacionesPorServicios();
    PrPrestaciones pol2 = new PrPrestaciones();
    PrPrestacionesJpaController pr = new PrPrestacionesJpaController(EntityManagerUtil.ObtenerEntityManager());
    List<PrPrestaciones> pr2;
    InPrestacionesPorServiciosJpaController pxs = new InPrestacionesPorServiciosJpaController(EntityManagerUtil.ObtenerEntityManager());
    List<InPrestacionesPorServicios> lppus;
    VeUnidadServicioJpaController us1 = new VeUnidadServicioJpaController(EntityManagerUtil.ObtenerEntityManager());
    List<VeUnidadServicio> us2;
    PrPrestaciones proc;
    SeUsuarios usu;
    SeEmpresa emp;
    SeSucursal suc;
    Long id;
    InPrestacionesPorServicios objps;

    public ActualizarPrestaciones(java.awt.Frame parent, boolean modal) {
        super(parent, modal = false);
        initComponents();
        setLocationRelativeTo(null);
        pr2 = pr.findPrPrestacionesEntities();
        us2 = us1.findVeUnidadServicioEntities();

    }

    public ActualizarPrestaciones(java.awt.Frame parent, boolean modal, SeUsuarios us, SeEmpresa em, SeSucursal su, InPrestacionesPorServicios obj) {
        super(parent, modal = false);
        setUndecorated(true);
        initComponents();
        setLocationRelativeTo(null);

        pr2 = pr.findPrPrestacionesEntities();
        us2 = us1.findVeUnidadServicioEntities();
        usu = us;
        emp = em;
        suc = su;
        objps = obj;

        Cargardatos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jguardarpreser = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cbxfacturable = new javax.swing.JComboBox<>();
        cbxaplicadescuento1 = new javax.swing.JComboBox<>();
        jsalir = new javax.swing.JButton();
        txtpresta = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtUnidadServicio = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        jLabel1.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        jLabel1.setText("NOMBRE:");

        jLabel2.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        jLabel2.setText("UNIDAD DE SERVICIO:");

        jguardarpreser.setBackground(new java.awt.Color(254, 254, 254));
        jguardarpreser.setFont(new java.awt.Font("Ubuntu", 1, 10)); // NOI18N
        jguardarpreser.setForeground(new java.awt.Color(1, 1, 1));
        jguardarpreser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/com/asofar/icon/GUARDAR_Mesa de trabajo 1.png"))); // NOI18N
        jguardarpreser.setText("GUARDAR");
        jguardarpreser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jguardarpreserActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        jLabel3.setText("FACTURABLE:");

        jLabel5.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        jLabel5.setText("APLICA DESCUENTO:");

        cbxfacturable.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        cbxfacturable.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SI", "NO" }));

        cbxaplicadescuento1.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        cbxaplicadescuento1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SI", "NO" }));

        jsalir.setBackground(new java.awt.Color(254, 254, 254));
        jsalir.setFont(new java.awt.Font("Ubuntu", 1, 10)); // NOI18N
        jsalir.setForeground(new java.awt.Color(1, 1, 1));
        jsalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/com/asofar/icon/salir_Mesa de trabajo 10.jpg"))); // NOI18N
        jsalir.setText("SALIR");
        jsalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jsalirActionPerformed(evt);
            }
        });

        txtpresta.setEditable(false);
        txtpresta.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N

        jLabel4.setBackground(java.awt.Color.red);
        jLabel4.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(254, 254, 254));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("PRESTACIONES - SERVICIO");
        jLabel4.setAutoscrolls(true);
        jLabel4.setOpaque(true);
        jLabel4.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jLabel4MouseDragged(evt);
            }
        });
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel4MousePressed(evt);
            }
        });

        txtUnidadServicio.setEditable(false);
        txtUnidadServicio.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel2))
                        .addGap(24, 24, 24)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbxaplicadescuento1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtUnidadServicio, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(cbxfacturable, javax.swing.GroupLayout.Alignment.LEADING, 0, 170, Short.MAX_VALUE))
                            .addComponent(txtpresta, javax.swing.GroupLayout.DEFAULT_SIZE, 443, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(131, 131, 131)
                        .addComponent(jsalir, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(98, 98, 98)
                        .addComponent(jguardarpreser, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtpresta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtUnidadServicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbxfacturable, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbxaplicadescuento1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jguardarpreser, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jsalir, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void jguardarpreserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jguardarpreserActionPerformed
        InPrestacionesPorServicios objPresxServ = new InPrestacionesPorServicios();

        java.util.Date fechaActual = new java.util.Date();

        objPresxServ = objps;

        objPresxServ.setEstado("A");
        objPresxServ.setEsFacturable(cbxfacturable.getSelectedItem().toString());
        objPresxServ.setAplicaDescuento(cbxaplicadescuento1.getSelectedItem().toString());
        objPresxServ.setUsuarioActualizacion(usu.getUsuario());
        objPresxServ.setFechaActualizacion(fechaActual);
        try {
            pxs.edit(objPresxServ);
            JOptionPane.showMessageDialog(null, "GUARDADO EXITOSAMENTE");
            setVisible(false);
            ConsultaPrestacionesporServicio cps = new ConsultaPrestacionesporServicio(new javax.swing.JFrame(), true, usu, emp, suc);
            cps.setVisible(true);
            cps.cargartabla();

        } catch (Exception ex) {
            Logger.getLogger(ActualizarPrestaciones.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jguardarpreserActionPerformed

    private void jLabel4MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseDragged
        Point point = MouseInfo.getPointerInfo().getLocation();
        setLocation(point.x - x, point.y - y);
    }//GEN-LAST:event_jLabel4MouseDragged

    private void jLabel4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MousePressed
        x = evt.getX();
        y = evt.getY();
    }//GEN-LAST:event_jLabel4MousePressed

    private void jsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jsalirActionPerformed

        setVisible(false);
        ConsultaPrestacionesporServicio cps = new ConsultaPrestacionesporServicio(new javax.swing.JFrame(), true, usu, emp, suc);
        cps.setVisible(true);

    }//GEN-LAST:event_jsalirActionPerformed

    public void Cargardatos() {

        PrPrestaciones objPRES;

        objPRES = pr.findPrPrestaciones(objps.getInPrestacionesPorServiciosPK().getIdPrestacion());

        txtpresta.setText(objPRES.getNombrePrestacion());

        VeUnidadServicio objUS;

        objUS = us1.findVeUnidadServicio(objps.getVeUnidadServicio().getIdUnidadServicio());

        txtUnidadServicio.setText(objUS.getNombreUnidadServicio());

        if (objps.getEsFacturable().equals("SI")) {
            cbxfacturable.setSelectedIndex(0);
        } else {
            cbxfacturable.setSelectedIndex(1);
        }

        if (objps.getAplicaDescuento().equals("SI")) {
            cbxaplicadescuento1.setSelectedIndex(0);
        } else {
            cbxaplicadescuento1.setSelectedIndex(1);
        }

    }

    public static void main(String args[]) {

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ActualizarPrestaciones dialog = new ActualizarPrestaciones(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbxaplicadescuento1;
    private javax.swing.JComboBox<String> cbxfacturable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jguardarpreser;
    private javax.swing.JButton jsalir;
    private javax.swing.JTextField txtUnidadServicio;
    public javax.swing.JTextField txtpresta;
    // End of variables declaration//GEN-END:variables
}
