/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.com.asofar.views.prestacionesporservicios;

import ec.com.asofar.dao.InPrestacionesPorServiciosJpaController;
import ec.com.asofar.dao.PrPrestacionesJpaController;
import ec.com.asofar.dao.VeUnidadServicioJpaController;
import ec.com.asofar.daoext.ObtenerDTO;
import ec.com.asofar.daoext.ValidarDTO;
import ec.com.asofar.dto.InPrestacionesPorServicios;
import ec.com.asofar.dto.PrArticulo;
import ec.com.asofar.dto.PrPrestaciones;
import ec.com.asofar.dto.PrSubgrupos;
import ec.com.asofar.dto.SeEmpresa;
import ec.com.asofar.dto.SeSucursal;
import ec.com.asofar.dto.SeUsuarios;
import ec.com.asofar.dto.VeUnidadServicio;
import ec.com.asofar.util.EntityManagerUtil;
import ec.com.asofar.views.prestaciones.Listar_Prestaciones;
import java.awt.MouseInfo;
import java.awt.Point;
import java.math.BigInteger;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import static jdk.nashorn.internal.runtime.Debug.id;

public class AgregarPrestaciones extends javax.swing.JDialog {
    int x,y;
    InPrestacionesPorServicios pol1 = new InPrestacionesPorServicios();
    PrPrestaciones pol2 = new PrPrestaciones();
    VeUnidadServicio pol3 = new VeUnidadServicio();

    PrPrestacionesJpaController pr = new PrPrestacionesJpaController(EntityManagerUtil.ObtenerEntityManager());
    List<PrPrestaciones> pr2;

    InPrestacionesPorServiciosJpaController pxs = new InPrestacionesPorServiciosJpaController(EntityManagerUtil.ObtenerEntityManager());
    List<InPrestacionesPorServicios> lppus;
    VeUnidadServicioJpaController us1 = new VeUnidadServicioJpaController(EntityManagerUtil.ObtenerEntityManager());
    List<VeUnidadServicio> us2;
    PrPrestaciones proc;
    SeUsuarios usu;
    SeEmpresa emp;
    SeSucursal suc;
     Long id;
     

    public AgregarPrestaciones(java.awt.Frame parent, boolean modal) {

        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        pr2 = pr.findPrPrestacionesEntities();
        nombrePrestacion(pr2);
        us2 = us1.findVeUnidadServicioEntities();
        nombreUnidad(us2);
//        lppus = pxs.findInPrestacionesPorServiciosEntities();
        cargarPrest();
        cargarUnida();
    }

    public void cargarPrest() {
        for (int i = 0; i < pr2.size(); i++) {
            System.out.println(" " + pr2.get(i).getNombrePrestacion());
        }
    }

    public void cargarUnida() {
        for (int i = 0; i < us2.size(); i++) {
            System.out.println("uni " + us2.get(i).getNombreUnidadServicio());
        }
    }

    public AgregarPrestaciones(java.awt.Frame parent, boolean modal, SeUsuarios us, SeEmpresa em, SeSucursal su) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        pr2 = pr.findPrPrestacionesEntities();
        nombrePrestacion(pr2);

        us2 = us1.findVeUnidadServicioEntities();
        nombreUnidad(us2);
        usu = us;
        emp = em;
        suc = su;  
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cbxunidadservicio = new javax.swing.JComboBox<>();
        jguardarpreser = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cbxfacturable = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        cbxaplicadescuento1 = new javax.swing.JComboBox<>();
        jsalir = new javax.swing.JButton();
        cbxestado = new javax.swing.JComboBox<>();
        jbotonbuscar = new javax.swing.JToggleButton();
        txtpresta = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        jLabel1.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        jLabel1.setText("NOMBRE:");

        jLabel2.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        jLabel2.setText("UNIDAD DE SERVICIO:");

        cbxunidadservicio.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        cbxunidadservicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxunidadservicioActionPerformed(evt);
            }
        });

        jguardarpreser.setFont(new java.awt.Font("Ubuntu", 1, 12)); // NOI18N
        jguardarpreser.setForeground(new java.awt.Color(74, 126, 72));
        jguardarpreser.setText("GUARDAR");
        jguardarpreser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jguardarpreserActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        jLabel3.setText("FACTURABLE:");

        jLabel5.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        jLabel5.setText("APLICA DESCUENTO:");

        cbxfacturable.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        cbxfacturable.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SI", "NO" }));
        cbxfacturable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxfacturableActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        jLabel6.setText("ESTADO:");

        cbxaplicadescuento1.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        cbxaplicadescuento1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SI", "NO" }));

        jsalir.setBackground(new java.awt.Color(160, 52, 58));
        jsalir.setFont(new java.awt.Font("Ubuntu", 1, 12)); // NOI18N
        jsalir.setForeground(new java.awt.Color(254, 254, 254));
        jsalir.setText("SALIR");
        jsalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jsalirActionPerformed(evt);
            }
        });

        cbxestado.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        cbxestado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A", "I" }));

        jbotonbuscar.setFont(new java.awt.Font("Ubuntu", 1, 12)); // NOI18N
        jbotonbuscar.setText("BUSCAR");
        jbotonbuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbotonbuscarActionPerformed(evt);
            }
        });

        txtpresta.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        txtpresta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtprestaActionPerformed(evt);
            }
        });

        jLabel4.setBackground(new java.awt.Color(255, 102, 0));
        jLabel4.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(254, 254, 254));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("PRESTACIONES - SERVICIO");
        jLabel4.setAutoscrolls(true);
        jLabel4.setOpaque(true);
        jLabel4.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jLabel4MouseDragged(evt);
            }
        });
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel4MousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel3))
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cbxfacturable, 0, 159, Short.MAX_VALUE)
                            .addComponent(cbxunidadservicio, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtpresta))
                        .addGap(18, 18, 18)
                        .addComponent(jbotonbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(jguardarpreser, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45)
                        .addComponent(jsalir, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel6)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(cbxestado, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel5)
                            .addGap(25, 25, 25)
                            .addComponent(cbxaplicadescuento1, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtpresta, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jbotonbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbxunidadservicio, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbxfacturable, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbxaplicadescuento1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addComponent(cbxestado, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel6)
                        .addGap(53, 53, 53)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jguardarpreser, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE)
                    .addComponent(jsalir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void jguardarpreserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jguardarpreserActionPerformed

        InPrestacionesPorServicios preServ = new InPrestacionesPorServicios();

      java.util.Date fechaActual = new java.util.Date();
       
        pol2 = ObtenerDTO.ObtenerPrPrestaciones(txtpresta.getText());
        pol3 = ObtenerDTO.ObtenerVeUnidadServicio(cbxunidadservicio.getSelectedItem().toString());

 
        try {
            boolean valor1=ValidarDTO.ValidarPreporservi(txtpresta.getText());
            if (valor1 == true) {
                JOptionPane.showMessageDialog(this, " YA EXISTENTE");
            } else {
                String valor ="I";
                
//        InPrestacionesPorServicios prest2 =new InPrestacionesPorServicios();
        
        if(cbxestado.getSelectedIndex() == 0){
            valor="A";
        }
       // sub = ObtenerDTO.ObtenerPrSubGrupos(subgrupo.getSelectedItem().toString());
        
                preServ.setPrPrestaciones(pol2);
                preServ.setVeUnidadServicio(pol3);
                preServ.setEsFacturable(cbxfacturable.getSelectedItem().toString());
                preServ.setAplicaDescuento(cbxestado.getSelectedItem().toString());
                preServ.setEstado(cbxestado.getSelectedItem().toString());
                preServ.setFechaCreacion(fechaActual);
                pxs.create(preServ);
                JOptionPane.showMessageDialog(null, " GUARDADO CON EXITO");
                setVisible(false);
       // control2.create( preServ);
              // JOptionPane.showMessageDialog(this, " "); 
             //  Actualizar();
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        
        
//            boolean valor1 = ValidarDTO.ValidarPreporservi(txtpresta.getText().toString())
//                && ValidarDTO.ValidarPrPrestaciones(txtpresta.getText().toString())
//                && ValidarDTO.ValidarPrPrestaciones(cbxunidadservicio.getSelectedItem().toString());
//
//        if (valor1 == true) {
//            JOptionPane.showMessageDialog(this, "Prestacion Ya existente");
//
//        } else {
//
//            preServ.setPrPrestaciones(pol2);
//            preServ.setVeUnidadServicio(pol3);
//            preServ.setEsFacturable(cbxfacturable.getSelectedItem().toString());
//            preServ.setAplicaDescuento(cbxestado.getSelectedItem().toString());
//            preServ.setEstado(cbxestado.getSelectedItem().toString());
//            preServ.setFechaCreacion(fechaActual);
//
//            try {
//                preServ.setPrPrestaciones(pol2);
//                preServ.setVeUnidadServicio(pol3);
//                preServ.setEsFacturable(cbxfacturable.getSelectedItem().toString());
//                preServ.setAplicaDescuento(cbxestado.getSelectedItem().toString());
//                preServ.setEstado(cbxestado.getSelectedItem().toString());
//                preServ.setFechaCreacion(fechaActual);
//                pxs.create(preServ);
//                JOptionPane.showMessageDialog(null, " GUARDADO CON EXITO");
//                setVisible(false);
//            } catch (Exception e) {
//                Logger.getLogger(AgregarPrestaciones.class.getName()).log(Level.SEVERE, null, e);
//            }
//
//        }

    }//GEN-LAST:event_jguardarpreserActionPerformed
    public void nombrePrestacion(List<PrPrestaciones> pr2) {
        
        lppus = pxs.findInPrestacionesPorServiciosEntities();
        for (int i = 0; i < pr2.size(); i++) {
//        cbxprestacion.addItem(pr2.get(i).getNombrePrestacion());
        }
    }

    public void nombreUnidad(List<VeUnidadServicio> us2) {
        
        for (int i = 0; i < us2.size(); i++) {
            cbxunidadservicio.addItem(us2.get(i).getNombreUnidadServicio());
        }
    }
    private void jLabel4MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseDragged
        Point point = MouseInfo.getPointerInfo().getLocation();
        setLocation(point.x-x,point.y-y);
    }//GEN-LAST:event_jLabel4MouseDragged

    private void jLabel4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MousePressed
        x = evt.getX();
        y = evt.getY();
    }//GEN-LAST:event_jLabel4MousePressed

    private void cbxunidadservicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxunidadservicioActionPerformed


    }//GEN-LAST:event_cbxunidadservicioActionPerformed

    private void cbxfacturableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxfacturableActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxfacturableActionPerformed

    private void jsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jsalirActionPerformed

        setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_jsalirActionPerformed

    private void jbotonbuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbotonbuscarActionPerformed
        setVisible(true);
        ConsultaPrestacion cp = new ConsultaPrestacion(new javax.swing.JFrame(), true);
        cp.setVisible(true);
        
         proc = cp.getPrestacion();
        txtpresta.setText(proc.getNombrePrestacion());
        id = proc.getIdPrestacion();
        
        
        
    }//GEN-LAST:event_jbotonbuscarActionPerformed

    private void txtprestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtprestaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtprestaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AgregarPrestaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AgregarPrestaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AgregarPrestaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AgregarPrestaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                AgregarPrestaciones dialog = new AgregarPrestaciones(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbxaplicadescuento1;
    private javax.swing.JComboBox<String> cbxestado;
    private javax.swing.JComboBox<String> cbxfacturable;
    private javax.swing.JComboBox<String> cbxunidadservicio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JToggleButton jbotonbuscar;
    private javax.swing.JButton jguardarpreser;
    private javax.swing.JButton jsalir;
    public javax.swing.JTextField txtpresta;
    // End of variables declaration//GEN-END:variables
}
