/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.com.asofar.views.DetallesTarifa;

import ec.com.asofar.dao.PrDetalleTarifarioJpaController;
import ec.com.asofar.dao.PrTarifarioJpaController;
import ec.com.asofar.dto.PrDetalleTarifario;
import ec.com.asofar.dto.PrTarifario;

import ec.com.asofar.dto.SeEmpresa;
import ec.com.asofar.dto.SeSucursal;
import ec.com.asofar.dto.SeUsuarios;
import ec.com.asofar.util.EntityManagerUtil;
import ec.com.asofar.util.Tablas;
import java.util.List;

/**
 *
 * @author Luis Alberto Mero
 */
public class CargarTarifario extends javax.swing.JDialog {

    PrTarifarioJpaController P = new PrTarifarioJpaController(EntityManagerUtil.ObtenerEntityManager());
    List<PrTarifario> lista = P.findPrTarifarioEntities();
    PrTarifario objeto = new PrTarifario();
    PrTarifario obj;
    AgregarNuevoDetalle pre = new AgregarNuevoDetalle(new javax.swing.JFrame(), true);

    /**
     * Creates new form CargarTarifario
     */
    SeUsuarios usu;
    SeEmpresa emp;
    SeSucursal suc;

    public CargarTarifario(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        System.out.println("************");
        Tablas.listarTarifario(lista, tbltarifario);
    }

    public CargarTarifario(java.awt.Frame parent, boolean modal, SeUsuarios us, SeEmpresa em, SeSucursal su, PrTarifario tr) {
        super(parent, modal);
        initComponents();
        System.out.println("************");
        Tablas.listarTarifario(lista, tbltarifario);

        usu = us;
        emp = em;
        suc = su;
    }

    public void MostrarTabla() {
        try {

            lista = P.findPrTarifarioEntities();
            Tablas.listarTarifario(lista, tbltarifario);
        } catch (Exception e) {
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbltarifario = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tbltarifario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbltarifario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tbltarifarioMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(tbltarifario);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 596, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(49, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tbltarifarioMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbltarifarioMousePressed

        int i = 0;
        if (evt.getClickCount() == 2) {

            i = tbltarifario.getSelectedRow();
            objeto = devuelveObjeto(tbltarifario.getValueAt(i, 0).toString(), lista);
            System.out.println("ide" + objeto.getPrTarifarioPK().getIdTarifario());
//            pre.txtidtarifario.setText(String.valueOf(objeto.getPrTarifarioPK().getIdTarifario()));
            if (objeto != null) {
                this.setVisible(false);
                Listar_PrestacionesPorServicio cp = new Listar_PrestacionesPorServicio(new javax.swing.JFrame(), true,usu,emp,suc, objeto);
                cp.setVisible(true);
            }

        }

        // TODO add your handling code here:
    }//GEN-LAST:event_tbltarifarioMousePressed

    public PrTarifario getObji() {
        return obj;
    }

    public void setObji(PrTarifario obj) {
        this.obj = obj;
    }

    public PrTarifario getTarifario() {
        return objeto;
    }

    public PrTarifario devuelveObjeto(String datos, List<PrTarifario> listaobjeto) {

        PrTarifario objeto1 = null;

        for (int i = 0; i < listaobjeto.size(); i++) {

            if (datos.equals("" + listaobjeto.get(i).getPrTarifarioPK().getIdTarifario())) {
                objeto1 = listaobjeto.get(i);

                break;

            }

        }

        return objeto1;

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CargarTarifario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CargarTarifario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CargarTarifario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CargarTarifario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                CargarTarifario dialog = new CargarTarifario(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbltarifario;
    // End of variables declaration//GEN-END:variables
}
